services:
  api:
    build: ./
    env_file: .env
    ports:
      - "$API_PORT:3000"             
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d # Montar el script de inicialización
