services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always 
    env_file: .env
    ports:
      - "$MONGODB_PORT:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d # Montar el script de inicialización

  api:
    container_name: api_node
    volumes:
      - .:/app
    restart: always
    build: .
    env_file: .env
    ports:
      - "$API_PORT:3000"             
    links:
      - mongodb